name: Build data files

on:
  workflow_dispatch:
  schedule:
    - cron: '45 12 */1 * *'

permissions:
  contents: write
  id-token: write

jobs:
  build_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        node-version: 22
        
    - name: Install dependencies
      run: npm install

    - name: Build commits
      run: npm run build-commits

    - name: Build data
      run: npm run build-data

    - name: Commit files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m "Automated data update $(date -u +'%Y-%m%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}