name: Build data files

on:
  workflow_dispatch:
  schedule:
    - cron: '45 12 */1 * *'

permissions:
  contents: write
  id-token: write
  
concurrency:
  cancel-in-progress: true

jobs:
  build_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        node-version: 20
    - run: npm install
    - run: npm run build-data